### ISSUE TITLE
Updating libraries causes style and behaviour problem with Test Window

### ISSUE THREAD

**Issue by vanavaraVL** [yaohuang/WebApiTestClient#23]
Good day of time!

After updating packages below it causes problem with test main window - styles css are moved elements incorrectly. Promblem with jQuery.UI i think.

Requeured - ok
jQuery 1.7.1
jQuery.UI.Combined 1.8.20
knockoutjs 2.1.0

Updating
jQuery 3.1.1
jQuery.UI.Combined 1.12.1
knockoutjs 3.4.0

**Comment by davidsmithgf** [comment]
What I did to solve the problem:
1. Uninstall-Package jQuery -Force
2. Install-Package jQuery -Version 1.10.2

**Comment by vanavaraVL** [comment]
check the version, the problem has solved.
thanks
