### ISSUE TITLE
Firefox issue

### ISSUE THREAD

**Issue by rbrock** [yaohuang/WebApiTestClient#5]
In my firefox test client doesn't work but in my chrome works fine...

**Comment by yaohuang** [comment]
Hi rbrock, can you tell me which version of firefox are you using?

**Comment by rbrock** [comment]
This is the page that I'm trying to test...

http://uattss.obione.us/Help/Api/POST-api-Login

At firefox I got error 500

Enviado via iPhone

Em 09/02/2013, às 15:04, yaohuang notifications@github.com escreveu:

**Comment by yaohuang** [comment]
yeah, I can see the 500 on your service but I can't really repro using a simple service like below. Can you tell me the actually exception message thrown by the server? I debugged with firebug and I can't spot anything wrong with the request sent by the test client.

```
public class Login
{
    public string Name { get; set; }
    public string  Password { get; set; }
}

public class ValuesController : ApiController
{
    // POST api/values
    public Login Post(Login value)
    {
        return value;
    }
}
```

**Comment by rbrock** [comment]
follow the screenshots

at Firefox http://i.imgur.com/z7Uk5EL.png
at Chrome http://i.imgur.com/gMhXPfR.png

**Comment by yaohuang** [comment]
Hmm, somehow your service is choking on the following accept header sent by Firefox by default:
  Accept: text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8
Other browsers like Chrome/IE sends:
  Accept: _/_

To prove this, you can add an Accept header in the test client with the value "text/xml" on Firefox, and you'll get back 200.

Looks like you just found a bug on your service using the test client :)
