### ISSUE TITLE
Test client does not work after installing Web Api CORS nightly package

### ISSUE THREAD

**Issue by sbatty** [yaohuang/WebApiTestClient#8]
I was using your test client, awesome by the way, then followed your blog post "Try out ASP.NET Web API CORS support using the nightly builds" to enable CORS support. After installing nightly CORS package my project won't build. Errors are:

Error   1   'xxxxxx.Areas.HelpPage.XmlDocumentationProvider' does not implement interface member 'System.Web.Http.Description.IDocumentationProvider.GetResponseDocumentation(System.Web.Http.Controllers.HttpActionDescriptor)'

Error   2   'xxxxxx.Areas.HelpPage.XmlDocumentationProvider' does not implement interface member 'System.Web.Http.Description.IDocumentationProvider.GetDocumentation(System.Web.Http.Controllers.HttpControllerDescriptor)'

It would appear that the method signature has changed?

**Comment by DalSoft** [comment]
Match your package versions install the pre release version of help too:

Install-Package Microsoft.AspNet.WebApi.HelpPage -Pre

**Comment by yaohuang** [comment]
Yup, updating the help page package (Microsoft.AspNet.WebApi.HelpPage) should fix the issue.
Regards,
Yao

**Comment by thelastworm** [comment]
Thanks this help
Ivan

**Comment by pradeepasp** [comment]
It resolved the issue regarding  xmldocumentationprovider for me but while running i got this error. can any one help me? please refer attached image.
![error](https://cloud.githubusercontent.com/assets/13114544/8425858/e19ec762-1f27-11e5-8d35-ff83992bf4fa.PNG)

**Comment by sandee-13** [comment]
I am using VS2012, MVC 5.2.2.0, Web Api 2. I have just changed the all versions from 2.0.0.0 to 3.0.0.0 of the following section of Web.config resides inside the View folder of my project. It will fix the problem.

[web-config--snippet.txt](https://github.com/yaohuang/WebApiTestClient/files/1523046/web-config--snippet.txt)
  
I hope this helps.
